//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ibrala_medya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class anaicerik
    {
        public int id { get; set; }
        public string logo { get; set; }
        public string sliderfoto { get; set; }
        public string slidermetin { get; set; }
        public Nullable<int> hizmetana { get; set; }
        public Nullable<int> referanslarlogo { get; set; }
        public string bitirilenproje { get; set; }
        public Nullable<int> musyorum { get; set; }
        public string butunproje { get; set; }
        public string hizmetverilensektorler { get; set; }
        public string mutlumus { get; set; }
        public Nullable<int> iletisim { get; set; }
    
        public virtual hakkimizda hakkimizda { get; set; }
        public virtual hizmetlerimiz hizmetlerimiz { get; set; }
        public virtual iletisim iletisim1 { get; set; }
        public virtual referanslar referanslar { get; set; }
    }
}
