//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ibrala_medya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class calisanlarimiz
    {
        public calisanlarimiz()
        {
            this.hakkimizda = new HashSet<hakkimizda>();
        }
    
        public int cid { get; set; }
        public string baslikbgresim { get; set; }
        public string sayfabaslik { get; set; }
        public string calisanfoto { get; set; }
        public string calisanadi { get; set; }
        public string calisansoyadi { get; set; }
        public string calisangorevi { get; set; }
        public string calisanhakkinda { get; set; }
        public bool aktif_pasif { get; set; }
        public Nullable<bool> onecikar { get; set; }
    
        public virtual ICollection<hakkimizda> hakkimizda { get; set; }
    }
}
