//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ibrala_medya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hakkimizda
    {
        public hakkimizda()
        {
            this.anaicerik = new HashSet<anaicerik>();
        }
    
        public int haid { get; set; }
        public string baslikbgresim { get; set; }
        public string sayfabaslik { get; set; }
        public string icerikresim { get; set; }
        public string icerikbaslik { get; set; }
        public string icerikmetin { get; set; }
        public string icerikmadde1 { get; set; }
        public string icerikmadde2 { get; set; }
        public string icerikmadde3 { get; set; }
        public string musteriyorum { get; set; }
        public string musterifoto { get; set; }
        public string musteriad { get; set; }
        public string musterisirketadi { get; set; }
        public bool aktif_pasif { get; set; }
        public Nullable<int> cid { get; set; }
        public Nullable<bool> onecikar { get; set; }
        public Nullable<int> rid { get; set; }
    
        public virtual ICollection<anaicerik> anaicerik { get; set; }
        public virtual calisanlarimiz calisanlarimiz { get; set; }
        public virtual referanslar referanslar { get; set; }
    }
}
