//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ibrala_medya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hizmetlerimiz
    {
        public hizmetlerimiz()
        {
            this.anaicerik = new HashSet<anaicerik>();
        }
    
        public int hid { get; set; }
        public string baslikbgresim { get; set; }
        public string sayfabaslik { get; set; }
        public string maddelogo { get; set; }
        public string maddebaslik { get; set; }
        public string maddeaciklama { get; set; }
        public string madde1 { get; set; }
        public string madde2 { get; set; }
        public string madde3 { get; set; }
        public string hizmetresim { get; set; }
        public string hizmetbaslik { get; set; }
        public string hizmetaciklama { get; set; }
        public bool aktif_pasif { get; set; }
        public Nullable<bool> onecikar { get; set; }
    
        public virtual ICollection<anaicerik> anaicerik { get; set; }
    }
}
