//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ibrala_medya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iletisim
    {
        public iletisim()
        {
            this.anaicerik = new HashSet<anaicerik>();
        }
    
        public int iid { get; set; }
        public string baslikbgresim { get; set; }
        public string sayfabaslik { get; set; }
        public string ekstrabaslik { get; set; }
        public string iletisimbaslik { get; set; }
        public string adres { get; set; }
        public string telefon1 { get; set; }
        public string telefon2 { get; set; }
        public string mail1 { get; set; }
        public string mail2 { get; set; }
        public string twitter { get; set; }
        public string facebook { get; set; }
        public string instagram { get; set; }
        public string linkedin { get; set; }
        public string youtube { get; set; }
        public string konumbilgisi { get; set; }
        public bool aktif_pasif { get; set; }
    
        public virtual ICollection<anaicerik> anaicerik { get; set; }
    }
}
