//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ibrala_medya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class referanslar
    {
        public referanslar()
        {
            this.anaicerik = new HashSet<anaicerik>();
            this.hakkimizda = new HashSet<hakkimizda>();
        }
    
        public int rid { get; set; }
        public string baslikbgresim { get; set; }
        public string sayfabaslik { get; set; }
        public string referanslogo { get; set; }
        public string referansadi { get; set; }
        public bool aktif_pasif { get; set; }
        public Nullable<bool> onecikar { get; set; }
    
        public virtual ICollection<anaicerik> anaicerik { get; set; }
        public virtual ICollection<hakkimizda> hakkimizda { get; set; }
    }
}
